### ISSUE TITLE
Questions about the dashboard

### ISSUE THREAD

**Issue by danielsl12** [ICST-Technion/F1CoreEngine#11]
1. Can we use open source products for the dashboard or do we need to develop an "in-house" solution?
2. What kind of data do we need to show in the dashboard? Do we want to show aggregations and graphs or to show it in a single log resolution?
3. What is the data upload rate? How much logs per second?
4. What is the format of the data? Does the data is pushed to the DB or pulled by it? Can we change the current code and format to make it more suitable?

**Comment by vMaroon** [comment]
1. Anything that works
2. Depends on what data. After understanding the data you're logging, the solution should be able to present at least aggregations given a query structure you provide
3. Realtime, which is at least 3 per second
4. The components you saw in the diagram output messages. Your solution must receive (exact "how" later) them and store them into the database you design. Your dashboard should be able to pull data from the DB, and perhaps also receive realtime messages (maybe a message bus that feeds both the dashboard's realtime windows and your receiver?)
You can manipulate the messages coming out of the components in whatever way you want, given that you retain the info packed within.

**Comment by danielsl12** [comment]
Hey @vMaroon , thank you for the quick answer. Can you iterate over your answer in q2?
> 2. Depends on what data. After understanding the data you're logging, the solution should be able to present at least aggregations given a query structure you provide

What do you mean depends on what data? Currently, we don't know what is even a possible data type and we didn't understand what the customer wants us to show in the final dashboard.
For example, what is the data we want to show at realtime? graphs? aggregations? logs that are being created right now?
If we want to show graphs, how do we present logs as graphs?
And for the stored data? Do we want to enable to send a query to the DB and show the result? Again, what kind of query (SQL? or something else). And how do we want to show the result that came back? only the logs in text? or graphs etc.

Thanks!

**Comment by vMaroon** [comment]
@danielsl12 I mean it will make more sense once the data is understood (the msg formats are available in the zip shared, and soon in accessible code repositories). 
When that happens, you'll better know what makes more sense to display, e.g. a graph would make sense if the data is a time-series of floats.

The "logs" are what you store in the database, in the format you see fit. If a component outputs the car's "world state", you may want to create a table with each variable as a column, or choose to dump it as-is as a jsonb... Again all these details will make more sense once you understand the outputs of the components, and think on what presentation makes most sense.
We can also always ask Sharon for her preferences, but I think it would be best if we come with concrete questions after better understanding the components.

For the latter, when the above is handled, you'll be able to better think of what data you're going to display, and what manipulation/querying you'll allow (though it will go through your pre-built query templates).

----

I think you should give the components a quick look and choose one that makes sense to aggregate and one that makes sense to graph and go from there, breaking dependencies/blocking tasks. Let's discuss the HLD and planning tomorrow.

**Comment by danielsl12** [comment]
@vMaroon , I missed that there is a file with all the message types.
I think that with your answers and the files I have a better understanding of what needs to be done.
Thank you very much!

**Comment by vMaroon** [comment]
NP

**Comment by danielsl12** [comment]
@vMaroon last question (hopefully),
Are the logs are going to be the messages we have in the files? 
Because when I was told about logs I thought about error/info/debug logs like "The file xxx was opened", "Failed to do some action" etc.
If all the logs are the messages, we can interpret them as a time series and easily show them as graphs over time.
Also, I saw that we have vectors in the messages, how do we want to show them over time?
Thanks.
