### ISSUE TITLE
Clonable TimesacleDB instance

### ISSUE THREAD

**Issue by danielsl12** [ICST-Technion/F1CoreEngine#26]
Anyone cloning the repository should have a simple way to setup the same
timescaleDB server as the one used by our project.

Any solution which allows for our TimescaleDB server setup to be uploaded to the repository
and reproduced simply will be accepted.

Also, create a docker-compose to be able to load the docker with all the wanted setting.

**Comment by SallyTurutov** [comment]
A simple way to set up the timescaleDB server and load the docker with all the wanted settings:
https://docs.timescale.com/install/latest/installation-docker/
