### ISSUE TITLE
Research Airsim Visual Simulation

### ISSUE THREAD

**Issue by shalevv123** [ICST-Technion/F1CoreEngine#5]
Subtask of https://github.com/ICST-Technion/F1CoreEngine/issues/4

Research the message format of the Airsim simulation:

what is its functionality?
input format?
output format?

**Comment by vMaroon** [comment]
https://github.com/Microsoft/AirSim/wiki/technion @shalevv123

**Comment by SallyTurutov** [comment]
# AirSim Simulator
## Functionality
The formula students' simulator of the car and the environment is based on AirSim. AirSim is a simulator for drones, cars, and more built on Unreal Engine. It supports visual and physical simulations. Moreover, training data can be generated from AirSim for deep learning.

AirSim exposes APIs so you can interact with the vehicle in the simulation programmatically. You can use these APIs to retrieve images, get state, control the vehicle and so on. The APIs are exposed through the RPC, and are accessible via a variety of languages, including C++, Python, C# and Java.

## Input & Output Format
The AirSim gets input from the Control (the wanted wheel angle, throttle wanted, etc), simulates the environment, and outputs it to the Preception.

*Airsim was a requirement by the client and thus swapping it for another simulation wasn't considered

**Comment by OmerAzriel** [comment]
Continuing this research is customer dependent and relies on the interfaces used in F1 code. therefore this issue is currently not closed.
