### ISSUE TITLE
Research Cognata Physical Simulation

### ISSUE THREAD

**Issue by shalevv123** [ICST-Technion/F1CoreEngine#7]
Subtask of https://github.com/ICST-Technion/F1CoreEngine/issues/4

Research the message format of the Cognata simulation:

what is its functionality?
input format?
output format?

**Comment by OmerAzriel** [comment]
Hi @vMaroon,
Does Cognata have a wiki page similar to the one you sent about Airsim? Also do we have permission to the formula git?

**Comment by OmerAzriel** [comment]
# Cognata Simulator
## Functionality

// need to list what are Cognata's products that are used in F1 (Sensor simulation or Closed Loop simulation, or both) (after getting access to F1 git).
// need to confirm these are the only sensors in use

Cognata is used to simulate these different sensors of the autonomous vehicle:
* Long distance camera
* IMU sensor
* LiDAR (?)
* Thermal Camera (?)
* GPS
* Radar (?)
* Camera
* Lens distortion models (?)
* CarMeasurments (?)

## Input & Output Format
Cognata gets input from the Control (Car measurements, location, speed, momentum & etc), simulates the sensors, and outputs it to the State Estimation.
// need to add ways of inputs and ouputs (after getting access to F1 git).

*Cognata was a requirement by the client and thus swapping it for another simulation wasn't considered

**Comment by OmerAzriel** [comment]
Hi @vMaroon, mentioning you again in case you didnt see. I dont think I can elaborate more on cognata without seeing how its used in the formula code. This product is not open source.

**Comment by OmerAzriel** [comment]
Continuing this research is customer dependent and relies on the interfaces used in F1 code. therefore this issue is currently not closed.
